#!/bin/bash

# Download and run the Guess which animal (https://github.com/CMPUT401-WI2021-GuessWhichAnimal/GuessWhichAnimal) server
# have cron run this with @reboot <path/to/script>

cd /home/ubuntu/animal_app
python3 manage.py migrate
python3 manage.py runserver
exit 0