#!/bin/bash

# Download and run the Guess which animal (https://github.com/CMPUT401-WI2021-GuessWhichAnimal/GuessWhichAnimal) server
# have cron run this with @reboot <path/to/script>

cd /home/ubuntu/animal_app
rm db.sqlite3
python3 manage.py migrate
echo "from play_game.loadcsv import load_animals; load_animals()" | python3 manage.py shell
sleep 180 #sleep 3 minutes so that ALLOWED_HOSTS gets populated correctly
python3 manage.py runserver [::]:8000
exit 0